import os
import time
import json
import requests
import sys

# Configuration via environment variables (No hardcoded secrets or local paths)
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
REPO_OWNER = os.environ.get("GITHUB_REPOSITORY_OWNER", "genesisgzdev")
REPO_NAME = os.environ.get("GITHUB_REPOSITORY_NAME", "threat-detection-suite")
LOG_FILE_PATH = os.environ.get("TDS_LOG_PATH", "/var/log/tds/threats.jsonl") # Default to standard Linux path, configurable for Windows

if not GITHUB_TOKEN:
    print("Error: GITHUB_TOKEN environment variable not set. Exiting.")
    sys.exit(1)

def create_github_issue(threat_data):
    url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/issues"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    title = f"[TDS Alert] {threat_data.get('severity', 'UNKNOWN')} Threat Detected: {threat_data.get('category', 'General')}"
    
    body = f"""
## Threat Detection Report

* **ID**: `{threat_data.get('id')}`
* **Severity**: `{threat_data.get('severity')}`
* **Category**: `{threat_data.get('category')}`
* **Timestamp**: `{threat_data.get('timestamp')}`
* **Associated PID**: `{threat_data.get('pid')}`

### Description
{threat_data.get('description', 'No description provided.')}

### Indicator of Compromise (IoC)
`{threat_data.get('ioc', 'N/A')}`

---
*Automated report generated by TDS Telemetry Engine.*
    """
    
    payload = {
        "title": title,
        "body": body,
        "labels": ["security", "automated-alert", threat_data.get('severity', 'low').lower()]
    }
    
    try:
        response = requests.post(url, headers=headers, json=payload, timeout=10)
        response.raise_for_status()
        print(f"Successfully created GitHub issue for threat ID {threat_data.get('id')}")
    except requests.exceptions.RequestException as e:
        print(f"Failed to create GitHub issue: {e}")

def tail_log_file(file_path):
    if not os.path.exists(file_path):
        print(f"Log file not found at {file_path}. Waiting for creation...")
        while not os.path.exists(file_path):
            time.sleep(5)
            
    with open(file_path, 'r') as file:
        # Seek to the end of the file to only process new events
        file.seek(0, os.SEEK_END)
        print(f"Tailing {file_path} for new threats in real-time...")
        
        while True:
            line = file.readline()
            if not line:
                time.sleep(0.5)
                continue
            
            try:
                threat_data = json.loads(line.strip())
                # Only report High and Critical threats to avoid API rate limits
                severity = threat_data.get('severity', '').upper()
                if severity in ['HIGH', 'CRITICAL']:
                    create_github_issue(threat_data)
            except json.JSONDecodeError:
                print("Failed to decode JSON line.")

if __name__ == "__main__":
    tail_log_file(LOG_FILE_PATH)
