name: Security Audit

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Snyk Test
        continue-on-error: true
        run: |
          npx --yes snyk code test --token=${{ secrets.SNYK_TOKEN }} || echo "Snyk audit completed with findings."
        
      - name: OSV-Scanner
        uses: google/osv-scanner-action/scan@v1
        continue-on-error: true
        with:
          scan-args: |-
            --recursive
            ./
